#!/bin/bash

CP=$(./gradlew -q --console plain printClasspath)

#     -Dgraal.LogVerbose=true \
#     -Dgraal.TraceTruffleStackTraceLimit=100 \
#     -Dgraal.TruffleCompilationThreshold=100 \
#     -Dgraal.TraceTruffleCompilationDetails=true \
#     -Dgraal.Dump=Truffle:2 \
#     -Dgraal.TraceTruffleCompilation=true \
java \
     -Dgraalvm.locatorDisabled=true \
     -Dgraal.TruffleFunctionInlining=true \
     -Dgraal.TruffleCompilationExceptionsArePrinted=true \
     -Xss8m \
     --add-opens org.graalvm.truffle/com.oracle.truffle.api=ALL-UNNAMED \
     --add-opens org.graalvm.truffle/com.oracle.truffle.api.interop=ALL-UNNAMED \
     --add-opens org.graalvm.truffle/com.oracle.truffle.api.nodes=ALL-UNNAMED \
     -classpath $CP \
     truffle.mal.${STEP:-stepE_macros} "$@"
